import test from 'node:test';import assert from 'node:assert/strict';
import {dealBlock,dealEmail,historyBlock} from '../api/_deal-followup-policy.js';
import {classify,followup} from '../api/_outreach-policy.js';
const p={pipeline:'914670001',dealstage:'1390230876'};
test('only open and lost Staffify opportunities qualify; meetings and refusal reasons hold',()=>{assert.equal(dealBlock(p),null);for(const id of ['1390230875','1402034032'])assert.ok(dealBlock({...p,dealstage:id}));assert.ok(dealBlock({...p,pipeline:'default'}));assert.ok(dealBlock({...p,closed_lost_reason:'Not interested'}));assert.ok(dealBlock({...p,hs_next_activity_date:'2099-01-01'}));});
test('lost reengagement never resets prior touches or bypasses replies and opt-outs',()=>{const sent=n=>Array.from({length:n},(_,i)=>({id:String(i),sent:true,to:['a@example.com'],from:'paul@trystaffify.com',mailbox:'paul@trystaffify.com',date:0}));assert.equal(historyBlock(sent(4),'a@example.com',[],classify),'sequence_complete_hold');assert.equal(historyBlock([...sent(1),{from:'a@example.com',text:'STOP',to:[],date:1}],'a@example.com',[],classify),'suppressed');assert.equal(historyBlock([...sent(1),{from:'a@example.com',text:'Can you tell me more?',to:[],date:1}],'a@example.com',[],classify),'human_reply_hold');assert.equal(historyBlock(sent(1),'a@example.com',[],classify),null);});
test('pending drafts, recent sends and cross-mailbox history prevent parallel outreach',()=>{assert.equal(historyBlock([{draft:true,to:[]}],'a@example.com',[],classify),'existing_draft_hold');assert.equal(historyBlock([{id:'a',sent:true,to:['a@example.com'],date:Date.now()}],'a@example.com',[],classify),'followup_not_due_hold');});
test('deal emails have distinct useful examples, no invented prior conversation and opt-out',()=>{const row={owner:'Madison',lane:'deal_followup',sentTouches:1};assert.equal(followup(row),dealEmail(row,1));for(let i=0;i<4;i++){assert.ok(dealEmail(row,i).includes('prefer no more emails'));assert.ok(!dealEmail(row,i).includes('—'));}assert.equal(new Set([0,1,2,3].map(i=>dealEmail(row,i))).size,4);});

test('historical bounces are held before enrollment',()=>{assert.equal(historyBlock([{from:'mailer-daemon@example.com',to:[],text:'failed'}],'a@example.com',[],classify),'bounce_hold');});
