import test from 'node:test';import assert from 'node:assert/strict';
import {engagementPlan,linkedinURL,ENGAGEMENT_STEPS} from '../api/_enterprise-engagement.js';
import {initialState,update} from '../api/_enterprise.js';
const now='2026-10-05T14:00:00Z';
function start(){let s=initialState();s=update(s,{action:'contact',id:'capital-one',name:'Test Buyer',role:'Procurement',source:'https://example.com/team',linkedin:'https://www.linkedin.com/in/test-buyer/'},'Paul',now);return update(s,{action:'engagement-start',id:'capital-one',contactName:'Test Buyer'},'Paul',now);}
test('LinkedIn profiles are individual HTTPS profiles, never lookalikes',()=>{assert.equal(linkedinURL('https://linkedin.com/in/test/?trk=abc'),'https://www.linkedin.com/in/test/');for(const v of ['https://linkedin.com.evil.test/in/x','javascript:bad','https://www.linkedin.com/company/test','http://linkedin.com/in/x'])assert.throws(()=>linkedinURL(v));});
test('one primary account plan, six steps and four email drafts',()=>{const s=start(),a=s.accounts[0],p=engagementPlan(a,Date.parse(now));assert.equal(p.steps.filter(s=>s.current).length,1);assert.equal(p.steps[0].state,'due');assert.equal(ENGAGEMENT_STEPS.filter(s=>s.channel==='Email').length,4);assert.throws(()=>update(s,{action:'engagement-start',id:a.id,contactName:'Test Buyer'},'Paul',now));});
test('recorded activity advances tasks without creating provider send evidence',()=>{let s=start();s=update(s,{action:'engagement-log',id:'capital-one',stepId:'connect',kind:'reported_complete',occurredAt:now,notes:'Invitation sent'},'Paul',now);const p=engagementPlan(s.accounts[0],Date.parse(now));assert.equal(p.steps[1].state,'scheduled');assert.equal(s.accounts[0].engagement.events[0].verification,'operator_reported');assert.equal(s.accounts[0].sentTouches,undefined);assert.throws(()=>update(s,{action:'engagement-log',id:'capital-one',stepId:'connect',kind:'reported_complete',occurredAt:now,notes:'duplicate'},'Paul',now));});
test('reply or opt-out stops every channel and generic status editing cannot remove the stop',()=>{for(const reason of ['reply','opt_out','meeting','client','human_owned']){let s=start();s=update(s,{action:'engagement-stop',id:'capital-one',reason,notes:'Reported conversation'},'Madison',now);s=update(s,{action:'account',id:'capital-one',owner:'Paul',status:'research'},'Paul',now);const p=engagementPlan(s.accounts[0],Date.parse(now));assert.equal(p.stop,reason);assert.equal(p.steps.filter(s=>s.current).length,0);assert.throws(()=>update(s,{action:'engagement-log',id:'capital-one',stepId:'connect',kind:'skipped',notes:'skip'},'Paul',now));}});
test('delayed actual activity moves the next task back and blocks early completion',()=>{let s=start();const late='2026-10-20T14:00:00Z';s=update(s,{action:'engagement-log',id:'capital-one',stepId:'connect',kind:'reported_complete',occurredAt:late,notes:'Completed today'},'Paul',late);assert.equal(engagementPlan(s.accounts[0],Date.parse(late)).steps[1].dueAt,'2026-10-23T14:00:00.000Z');assert.throws(()=>update(s,{action:'engagement-log',id:'capital-one',stepId:'email-1',kind:'reported_complete',occurredAt:late,notes:'Too early'},'Paul',late));});
