import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {financeAccess,financeMachine} from '../api/_finance-access.js';
test('financial access is restricted to verified Paul identities and Madison, never generic roles',()=>{for(const email of ['hello@gostaffify.com','paul@staffifyhq.com','madison@gostaffify.com'])assert.equal(financeAccess({email,role:'rep'}),true);for(const email of ['newhire@gostaffify.com','outsider@example.com','madison@staffifyhq.com'])assert.equal(financeAccess({email,role:'admin'}),false);assert.equal(financeAccess(null),false);});
test('machine financial access requires the scheduler bearer, never query identity or tokens',()=>{process.env.CRON_SECRET='test-only';assert.equal(financeMachine({headers:{authorization:'Bearer test-only'}}),true);assert.equal(financeMachine({headers:{},query:{token:'test-only',email:'hello@gostaffify.com'}}),false);delete process.env.CRON_SECRET;});
test('all financial routes enforce access before querying sources and do not trust open identity',()=>{for(const name of ['commissions','residuals','finance-snapshot']){const s=readFileSync(new URL('../api/'+name+'.js',import.meta.url),'utf8');assert.match(s,/financeAccess\(who\)/);assert.doesNotMatch(s,/await openIdentity/);assert.match(s,/403:401/);}});
test('financial page script parses and denies unauthorized accounts',()=>{const s=readFileSync(new URL('../commissions/index.html',import.meta.url),'utf8');const js=s.match(/<script>([\s\S]*?)<\/script>/)[1];assert.doesNotThrow(()=>new Function(js));assert.match(js,/if\(!ME.financeAccess\)/);});
import {onboardingAmount,invoicePayments} from '../api/_commission-evidence.js';
test('placement commissions exclude ordinary hours and subtract onboarding discounts',()=>{const line=(name,Amount)=>({Amount,SalesItemLineDetail:{ItemRef:{name}}});assert.equal(onboardingAmount({Line:[line('VA Staffing',2499),line('Hourly VA',5000),line('Action Taker Price',-500)]}),1999);assert.equal(onboardingAmount({Line:[line('Hourly VA',5000)]}),0);});
test('cash evidence is invoice-specific and ambiguous allocations are not guessed',()=>{assert.deepEqual(invoicePayments({Line:[{Amount:700,LinkedTxn:[{TxnType:'Invoice',TxnId:'a'}]},{Amount:300,LinkedTxn:[{TxnType:'Invoice',TxnId:'b'},{TxnType:'Invoice',TxnId:'c'}]}]}),[{invoiceId:'a',amount:700}]);});
test('anonymous requests cannot impersonate finance identities through any finance route',async()=>{process.env.KV_REST_API_URL='https://example.com';process.env.KV_REST_API_TOKEN='test';for(const name of ['commissions','residuals','finance-snapshot','finance-connection']){const handler=(await import('../api/'+name+'.js')).default;for(const email of ['hello@gostaffify.com','madison@gostaffify.com']){let code;const res={setHeader(){},status(n){code=n;return this;},json(v){return v;}};await handler({method:'GET',headers:{},query:{email,view:'admin',probe:'1'}},res);assert.equal(code,401,name);}}});
