import test from 'node:test';import assert from 'node:assert/strict';
import {applyMadisonPlan,residualTerms,eligibleResidualDay,sourceKind,ensureMadisonPlan} from '../api/_madison-commission-plan.js';
import {placementUnits} from '../api/_commission-evidence.js';
function line(n,source='house',extra={}){return {dealId:String(n),repEmail:'madison@gostaffify.com',dealType:'va',closeDate:'2026-09-'+String(n).padStart(2,'0'),invoiceId:'invoice'+n,placementUnits:[2100],commissionEligibleBase:2100,invoiceTotal:2100,leadSource:source,status:'payable',base:2100,outstanding:0,paymentSchedule:[],...extra};}
test('20% business, 30% self, fifth and subsequent 35%; first four are not retroactively repriced',()=>{const rows=applyMadisonPlan([line(1),line(2,'self'),line(3),line(4,'self'),line(5),line(6,'self')]);assert.deepEqual(rows.map(r=>r.rate),[20,30,20,30,35,35]);assert.deepEqual(rows.map(r=>r.commission),[420,630,420,630,735,735]);assert.equal(rows[5].monthlyVerifiedPlacements,6);});
test('monthly threshold resets, and instalments retain the sale month rate',()=>{const rows=applyMadisonPlan([line(1),line(2),line(3),line(4),line(5,'self',{base:700,paymentSchedule:[{amount:700,fee:0}]}),line(6,'self',{closeDate:'2026-10-01'})]);assert.equal(rows[4].commission,245);assert.equal(rows[4].paymentSchedule[0].commission,245);assert.equal(rows[5].commission,630);assert.equal(rows[5].monthlyPlacementsBefore,0);});
test('a multi-VA invoice crosses the threshold by units, not deal count',()=>{const rows=applyMadisonPlan([line(1),line(2),line(3),line(4,'house',{placementUnits:[2100,2100],base:4200})]);assert.deepEqual(rows[3].unitRates,[20,35]);assert.equal(rows[3].commission,1155);assert.equal(rows[3].monthlyVerifiedPlacements,5);});
test('duplicate invoices, missing placement proof and refunds do not advance the counter',()=>{const rows=applyMadisonPlan([line(1),line(2,'self',{invoiceId:'invoice1'}),line(3,'house',{placementUnits:[]}),line(4,'house',{refunded:true,status:'refund_review'}),line(5)]);assert.equal(rows[4].monthlyPlacementsBefore,1);assert.equal(rows[4].rate,20);assert.equal(rows[1].status,'placement_review');assert.equal(rows[3].commission,0);});
test('retry is idempotent and settled payouts are preserved',()=>{const rows=[line(1),line(2,'house',{status:'paid_out',commission:525,rate:25})];applyMadisonPlan(rows);const once=JSON.stringify(rows);applyMadisonPlan(rows);assert.equal(JSON.stringify(rows),once);assert.equal(rows[1].commission,525);});
test('unknown origin is held for review; arbitrary prospect text cannot claim the self-sourced rate',()=>{assert.equal(sourceKind('prospect'),'');const [row]=applyMadisonPlan([line(1,'')]);assert.equal(row.status,'source_review');assert.equal(row.leadSourceVerified,false);assert.equal(sourceKind('Madison-generated'),'self');});
test('Madison residuals remain $1/hour beyond six months, and pre-client hours are excluded',()=>{const window=residualTerms('madison@gostaffify.com','2026-01-01');assert.equal(window.perHour,1);assert.equal(window.to,null);assert.equal(eligibleResidualDay('2027-02-01',window),true);assert.equal(eligibleResidualDay('2025-12-31',window),false);assert.equal(eligibleResidualDay('2027-02-01',residualTerms('other@gostaffify.com','2026-01-01')),false);});
test('VA quantity comes from placement invoice items, never hourly or training quantity',()=>{assert.deepEqual(placementUnits({Line:[{Amount:4200,SalesItemLineDetail:{ItemRef:{name:'VA Staffing'},Qty:2}},{Amount:4000,SalesItemLineDetail:{ItemRef:{name:'Hourly VA'},Qty:200}},{Amount:500,SalesItemLineDetail:{ItemRef:{name:'Training (deleted)'},Qty:1}}]}),[2100,2100]);assert.deepEqual(placementUnits({Line:[{Amount:1000,SalesItemLineDetail:{ItemRef:{name:'VA Staffing'},Qty:0.5}}]}),[]);});
test('plan migration records previous settings, preserves identity, and only applies once',async()=>{const data=new Map([['rep:madison@gostaffify.com',{email:'madison@gostaffify.com',role:'rep',rate:'25'}]]);let writes=0;const redis={get:async k=>data.get(k),hgetall:async k=>data.get(k),set:async(k,v,o)=>{if(!o?.nx||!data.has(k))data.set(k,v);},hset:async(k,v)=>{writes++;data.set(k,{...data.get(k),...v});}};await ensureMadisonPlan(redis);await ensureMadisonPlan(redis);assert.equal(writes,1);assert.equal(data.get('rep:madison@gostaffify.com').role,'rep');assert.equal(data.get('rep:madison@gostaffify.com').houseRate,'20');assert.equal(data.get('rep:madison@gostaffify.com').rate,'30');assert.equal(data.get('rep:madison@gostaffify.com').residualPerHour,'1');});

test('multiple Madison placements for one client do not duplicate or lose residual hours',async()=>{const {indexResidualDeal}=await import('../api/_madison-commission-plan.js');const index={};indexResidualDeal(index,'client',{dealId:'first',ownerEmail:'madison@gostaffify.com',closeDate:'2026-01-01'});indexResidualDeal(index,'client',{dealId:'second',ownerEmail:'madison@gostaffify.com',closeDate:'2026-09-01'});assert.equal(index.client.dealId,'first');indexResidualDeal(index,'client',{dealId:'other',ownerEmail:'paul@staffifyhq.com',closeDate:'2026-08-01'});assert.equal(index.client,null);});
