import test from 'node:test';import assert from 'node:assert/strict';
import {mergeInventory,localBlock,dueInventory,inventorySummary,INVENTORY} from '../api/_outreach-inventory.js';
import {makeLeadPrep} from '../api/_outreach-lead-prep-core.js';
const item={email:'owner@example.com',company:'Example media',domain:'example.com',first:'Owner',country:'United States',region:'California',fit_review:'possible_media_needs_verification'};
const state={records:[],assignments:[],suppressions:[],pausedOwners:[]};
test('reimport deduplicates and preserves progress and exclusion evidence',()=>{let inv=mergeInventory(null,[item,{...item,email:'OWNER@example.com',known_history:'historic_campaign_send'}]);inv.records[0].result={reason:'held'};inv=mergeInventory(inv,[item]);assert.equal(inv.records.length,1);assert.equal(inv.records[0].result.reason,'held');assert.match(inv.records[0].known_history,/historic_campaign_send/);assert.equal(localBlock(inv.records[0],state),'Recovered exclusion or prior conversation');});
test('due selection avoids repeat charges until retry time; fresh records first',()=>{const inv={records:[{...item,result:{reason:'temporary'},nextAt:new Date(0).toISOString()},{...item,email:'new@example.com'},{...item,email:'future@example.com',result:{reason:'verified'},nextAt:new Date(Date.now()+86400000).toISOString()}]};assert.deepEqual(dueInventory(inv).map(r=>r.email),['new@example.com',item.email]);assert.equal(inventorySummary(inv).pending,2);});
test('sent records, suppressed contacts and paused Madison reservations never become new leads',()=>{assert.equal(localBlock(item,{...state,records:[{recipient:item.email,status:'sent',sentTouches:4}]}),'Existing sequence or protected hold');assert.equal(localBlock(item,{...state,suppressions:[item.email]}),'Global suppression');assert.equal(localBlock(item,{...state,assignments:[{email:item.email,owner:'Madison'}],pausedOwners:['Madison']}),'Owner paused');});
function harness({fit=true,client='clear',provider='verified',existing=null}={}){const db=new Map([[INVENTORY,{records:[structuredClone(item)]}],['queue',structuredClone(state)]]);let paid=0,created=0,patched=0,contact=existing;const ready=new Set();
 const redis={sadd:async(k,email)=>{ready.add(email);return 1;},get:async k=>structuredClone(db.get(k)),set:async(k,v,o)=>{if(o?.nx&&db.has(k))return null;db.set(k,structuredClone(v));return 'OK';},eval:async(script,keys,args)=>{if(script.includes('INCR'))return 1;if(db.get(keys[0])===args[0])db.delete(keys[0]);return 1;}};
 const hs=async(path,body,method)=>{if(path.includes('account-info'))return {portalId:51666712};if(path.startsWith('/crm/v3/objects/contacts?'))return {results:[]};if(path.endsWith('/search'))return body.filterGroups[0].filters[0].propertyName==='email'?{results:contact?[contact]:[]}:{results:[]};if(method==='PATCH'){patched++;contact.properties={...contact.properties,...body.properties};return contact;}created++;contact={id:'123',properties:body.properties};return contact;};
 const run=makeLeadPrep({redis,readBody:r=>r.body,config:async()=>({enabled:true}),draftBlockReason:async()=>null,site:async()=>({url:'https://example.com',text:fit?'real estate photography services':'a law office'}),verifyEmail:async()=>{paid++;return {status:provider,reason:'provider unavailable'};},isOptedOut:async()=>false,clientCheck:async()=>({status:client}),hs,KEY:'queue'});
 process.env.CRON_SECRET='test';return {db,ready,counts:()=>({paid,created,patched}),run:async()=>{let out;await run({headers:{authorization:'Bearer test'}},{setHeader(){},status(){return this},json(v){out=v;return v;}});return out;}};}
test('eligible recovered lead is verified, imported once, and saved across repeated runs',async()=>{const h=harness();const r=await h.run();assert.equal(r.verified,1);assert.equal(r.imported,1);assert.equal(h.ready.has(item.email),true);assert.deepEqual(h.counts(),{paid:1,created:1,patched:1});await h.run();assert.deepEqual(h.counts(),{paid:1,created:1,patched:1});});
test('bad fit and known clients spend no credits and create no CRM contact',async()=>{for(const options of [{fit:false},{client:'client'}]){const h=harness(options);await h.run();assert.deepEqual(h.counts(),{paid:0,created:0,patched:0});}});
test('provider outage leaves prospect pending and never enrolls it',async()=>{const h=harness({provider:'unavailable'});assert.equal((await h.run()).status,'provider_unavailable');assert.equal(h.counts().created,0);assert.equal(inventorySummary(h.db.get(INVENTORY)).pending,1);});
test('existing non-outreach CRM records are never reactivated',async()=>{const h=harness({existing:{id:'1',properties:{rep_lifecycle_state:'HUMAN_OWNED'}}});await h.run();assert.deepEqual(h.counts(),{paid:0,created:0,patched:0});});
import {publicIp} from '../api/_public-ip.js';
test('website lookup accepts public IPv6 but rejects private, mapped, tunnel and special-use addresses',()=>{for(const ip of ['2606:4700:3037::ac43:9d1a','2001:4860:4860::8888','8.8.8.8'])assert.equal(publicIp(ip),true,ip);for(const ip of ['::1','::ffff:127.0.0.1','fc00::1','fe80::1','2001:db8::1','2001:2::1','2002:7f00:1::','3fff::1','127.0.0.1','10.1.1.1','169.254.169.254'])assert.equal(publicIp(ip),false,ip);});
test('an unclassified existing contact can qualify without creating another CRM contact',async()=>{const h=harness({existing:{id:'1',properties:{email:item.email,company:item.company,website:item.domain,rep_lifecycle_state:''}}});const r=await h.run();assert.equal(r.verified,1);assert.deepEqual(h.counts(),{paid:1,created:0,patched:1});});
import {hubspotRequest} from '../api/_outreach-hubspot.js';
test('CRM 429 responses retry behind the shared request limiter',async()=>{let calls=0,slots=0;const waits=[];const result=await hubspotRequest('https://api.hubapi.com/test',{}, {redis:{eval:async()=>{slots++;return 350;}},sleep:async ms=>waits.push(ms),fetcher:async()=>{calls++;return new Response('{}',{status:calls===1?429:200,headers:{'retry-after':'2'}});}});assert.equal(result.status,200);assert.equal(calls,2);assert.equal(slots,2);assert.deepEqual(waits,[350,2000,350]);});
import {locationRefreshDeferred} from '../api/_outreach-send.js';
test('recent unknown locations cannot consume every sending tick, and refresh after 15 minutes',()=>{const now=Date.now();assert.equal(locationRefreshDeferred({prospectTimezone:{timeZone:null,checkedAt:new Date(now).toISOString()}},now),true);assert.equal(locationRefreshDeferred({prospectTimezone:{timeZone:null,checkedAt:new Date(now-16*60000).toISOString()}},now),false);assert.equal(locationRefreshDeferred({prospectTimezone:{timeZone:'America/New_York',checkedAt:new Date(now).toISOString()}},now),false);});
import {supplyOwner} from '../api/_outreach-inventory.js';
test('CRM owner survives recovery; unknown owners are held and reservations stay authoritative',()=>{const reps=[{hubspotOwnerId:'7',email:'madison@gostaffify.com'}];assert.equal(supplyOwner({crmOwnerId:'7',id:'2',reps}),'Madison');assert.equal(supplyOwner({crmOwnerId:'999',id:'2',reps}),null);assert.equal(supplyOwner({assigned:{owner:'Paul'},crmOwnerId:'7',id:'2',reps}),'Paul');});

test('CRM inventory uses list pagination beyond search 10000 cap and keeps cursor on failure',async()=>{
 const db=new Map([['queue',structuredClone(state)],['staffify:lead-prep:cursor','10020'],['staffify:lead-prep:list-cursor:v3','248499999999']]);let fail=false,seen;
 const redis={get:async k=>db.get(k),set:async(k,v)=>{db.set(k,v);return 'OK';},eval:async()=>1};
 const run=makeLeadPrep({redis,config:async()=>({enabled:true}),hs:async(path,body,method)=>{if(path.includes('account-info'))return {portalId:51666712};seen=new URL('https://api.hubapi.com'+path);assert.equal(method,'GET');assert.equal(seen.searchParams.get('after'),'248499999999');if(fail)throw Error('CRM unavailable (503)');return {results:[{id:'1',properties:{}}],paging:{next:{after:'248500000000'}}};},KEY:'queue'});
 const call=async()=>{let out;await run({headers:{authorization:'Bearer test'}},{setHeader(){},status(){return this;},json(v){out=v;}});return out;};process.env.CRON_SECRET='test';
 assert.equal((await call()).status,'complete');assert.equal(db.get('staffify:lead-prep:list-cursor:v3'),'248500000000');
 db.set('staffify:lead-prep:list-cursor:v3','248499999999');fail=true;assert.equal((await call()).status,'error');assert.equal(db.get('staffify:lead-prep:list-cursor:v3'),'248499999999');
});
