import test from 'node:test';import assert from 'node:assert/strict';import {eligible,quota,classify,dayKey} from '../api/_outreach-policy.js';
const now=Date.parse('2026-09-23T20:00:00Z');const row={owner:'Madison',sender:'madison@staffifyhq.com',recipient:'a@example.com',status:'sent',sentTouches:1,lastSentAt:new Date(now-48*3600000).toISOString()};const state={pausedOwners:[],suppressions:[]};
test('48h boundary and four total touches',()=>{assert.equal(eligible(row,state,now),true);assert.equal(eligible({...row,lastSentAt:new Date(now-47*3600000).toISOString()},state,now),false);assert.equal(eligible({...row,sentTouches:4},state,now),false);assert.equal(eligible({...row,status:'draft_saved'},state,now),false);});
test('Madison has an independent 50-total quota per mailbox including follow-ups',()=>{const c=Array.from({length:50},(_,i)=>({day:dayKey(now),owner:'Madison',sender:row.sender,touch:i%4+1}));assert.equal(quota(row,c,now),false);assert.equal(quota(row,c.slice(1),now),true);assert.equal(quota({...row,sender:'madison@trystaffify.com'},c,now),true);assert.equal(quota(row,c,now+86400000),true);});
test('suppression and pauses block both introductions and followups',()=>{assert.equal(eligible(row,{...state,suppressions:[row.recipient]},now),false);assert.equal(eligible(row,{...state,pausedOwners:['Madison']},now),false);assert.equal(eligible({...row,status:'prepared',sentTouches:0,bodyText:'hello'},state,now),false);});
test('all human or automatic replies hold; explicit refusal suppresses',()=>{const m={from:row.recipient,to:[row.sender],text:'Stop emailing me',sent:false};assert.equal(classify([m],row.recipient,[row.sender]).status,'suppressed');assert.equal(classify([{...m,text:'Yes, tell me more'}],row.recipient,[row.sender]).status,'human_reply_hold');});

import {automatedModeAllowed} from '../api/_outreach-policy.js';
test('CRM automated outreach mode remains eligible while human and unknown modes fail closed',()=>{assert.equal(automatedModeAllowed('AUTOMATED'),true);assert.equal(automatedModeAllowed(''),true);assert.equal(automatedModeAllowed('HUMAN_OWNED'),false);assert.equal(automatedModeAllowed('MANUAL'),false);assert.equal(automatedModeAllowed('unknown'),false);});

import {reconcileThread,callReady,replyText} from '../api/_outreach-policy.js';
const sentMessage=(id,date)=>({id,replyId:id,from:row.sender,to:[row.recipient],sent:true,text:'Useful handoff',date});
test('actual sent detection advances sequence and records full audit history',()=>{const r={...row,status:'draft_saved',sentTouches:0,draftId:'d1'};reconcileThread(r,[sentMessage('s1',now)],now);assert.equal(r.status,'sent');assert.equal(r.sentTouches,1);assert.equal(r.draftId,null);assert.equal(r.events[0].kind,'sent');assert.equal(eligible(r,state,now),false);});
test('manual removal does not regenerate a follow-up',()=>{const r={...row,status:'draft_saved',draftId:'d2'};reconcileThread(r,[sentMessage('s1',now-72*3600000)],now);assert.equal(r.status,'missing_draft_hold');assert.equal(eligible(r,state,now),false);});
test('four actual sends produce manual-call readiness only after 48h',()=>{const r={...row,sentTouches:3};reconcileThread(r,[0,1,2,3].map(i=>sentMessage('s'+i,now-(7-i*2)*86400000)),now);assert.equal(r.sentTouches,4);assert.equal(callReady(r,now),false);assert.equal(callReady(r,now+86400000),true);assert.equal(eligible(r,state,now+86400000),false);});
test('human reply cancels follow-up and manual call readiness',()=>{const r={...row,sentTouches:4};reconcileThread(r,[sentMessage('s',now-72*3600000),{id:'r',from:row.recipient,to:[row.sender],date:now,text:'Tell me more',sent:false}],now);assert.equal(r.status,'human_reply_hold');assert.equal(r.callReady,false);});
test('quoted opt-out footer does not turn a buying reply into an unsubscribe',()=>{const text='Yes, can we talk?\nOn Wednesday Paul wrote:\nTo unsubscribe, let me know.';assert.equal(replyText(text).trim(),'Yes, can we talk?');assert.equal(classify([{from:row.recipient,to:[row.sender],text}],row.recipient,[row.sender]).status,'human_reply_hold');assert.equal(classify([{from:row.recipient,to:[row.sender],text:'Please remove me'}],row.recipient,[row.sender]).status,'suppressed');});
test('forwarded copies do not inflate sent count',()=>{const m=sentMessage('s1',now);assert.equal(classify([m,{...m,id:'copy'}],row.recipient,[row.sender]).sent.length,1);});

test('equivalent refusals suppress globally while quoted refusals do not',()=>{for(const text of ["Please take me off your list", "No thank you", "Please don't contact me", "Not a good fit for us"]){assert.equal(classify([{from:row.recipient,to:[row.sender],text}],row.recipient,[row.sender]).status,'suppressed');}});
test('historical touch count alone cannot place someone on the call queue',()=>{const r={...row,sentTouches:4};reconcileThread(r,[sentMessage('s1',now-72*3600000)],now);assert.equal(r.sentTouches,4);assert.equal(r.verifiedSentTouches,1);assert.equal(callReady(r,now),false);});
