import {test} from 'node:test';import assert from 'node:assert/strict';import {incidents,checkAlerts,alertText} from '../api/_outreach-alerts.js';
const now=Date.parse('2026-10-01T14:00:00Z');const healthy=()=>({cfg:{enabled:true},run:{finishedAt:new Date(now).toISOString(),status:'complete'},health:{accounts:[{email:'test@example.com',ok:true}]},prep:{finishedAt:new Date(now).toISOString(),status:'complete'}});
function harness(){const map=new Map(),messages=[];return {redis:{get:async k=>map.get(k),set:async(k,v)=>map.set(k,structuredClone(v))},notify:async t=>{messages.push(t);return {ok:true};},messages};}
test('normal runs and intentional pause stay quiet',()=>{assert.deepEqual(incidents(healthy(),now),[]);assert.deepEqual(incidents({cfg:{enabled:false}},now),[]);});
test('stale worker and broken mailbox are independent actionable incidents',()=>{const s=healthy();s.run.finishedAt='2026-10-01T13:00:00Z';s.health.accounts[0].ok=false;assert.deepEqual(incidents(s,now).map(i=>i.id),['worker-overdue','mailbox-access']);});
test('two observations, deduplication, reminder and one recovery',async()=>{const h=harness(),s=healthy();s.run.status='error';for(const t of [now,now+300000,now+600000])await checkAlerts({...h,snapshot:s,now:t});assert.equal(h.messages.length,1);s.run.finishedAt=new Date(now+7*3600000).toISOString();s.prep.finishedAt=s.run.finishedAt;await checkAlerts({...h,snapshot:s,now:now+7*3600000});assert.equal(h.messages.length,2);await checkAlerts({...h,snapshot:healthy(),now});await checkAlerts({...h,snapshot:healthy(),now});assert.equal(h.messages.length,3);assert.match(h.messages[2],/recovered/);});
test('failed delivery retries and never pretends it was sent',async()=>{const h=harness(),s=healthy();s.run.status='error';let n=0;const notify=async()=>({ok:++n>1,error:'test'});await checkAlerts({...h,notify,snapshot:s,now});await checkAlerts({...h,notify,snapshot:s,now:now+1});await checkAlerts({...h,notify,snapshot:s,now:now+2});assert.equal(n,2);});
test('deliberate pause does not send a recovery',async()=>{const h=harness(),s=healthy();s.run.status='error';await checkAlerts({...h,snapshot:s,now});await checkAlerts({...h,snapshot:s,now:now+1});await checkAlerts({...h,snapshot:{cfg:{enabled:false}},now:now+2});assert.equal(h.messages.length,1);});
test('untrusted values cannot create Slack mentions',()=>{assert.doesNotMatch(alertText({title:'<!channel>',impact:'a',action:'b'}),/<!channel>/);});
