import test from 'node:test';
import assert from 'node:assert/strict';
import {makeWorker} from '../api/_outreach-worker-core.js';
import * as policy from '../api/_outreach-policy.js';
function harness({record,mailboxFailed=false,createUncertain=false}={}){
 const key='queue',calls=[];const initial={revision:1,records:record?[record]:[],assignments:[],suppressions:[],pausedOwners:[],creations:[],updatedAt:new Date().toISOString()};const db=new Map([[key,structuredClone(initial)]]);
 const redis={get:async k=>structuredClone(db.get(k)),set:async(k,v,o)=>{if(o?.nx&&db.has(k))return null;db.set(k,structuredClone(v));return 'OK';},eval:async(script,keys,args)=>{if(script.includes('cjson.decode')){if(db.get(key).revision!==Number(args[0]))return 0;db.set(key,JSON.parse(args[1]));return 1;}if(db.get(keys[0])===args[0])db.delete(keys[0]);return 1;}};
 const sender='paul@trystaffify.com';const prior={id:'sent1',replyId:'sent1',mailbox:sender,threadId:'thread',from:sender,to:['prospect@example.com'],sent:true,text:'hello',date:Date.now()-72*3600000};let draft={id:'draft',message:{id:'msg',threadId:'thread',labelIds:['DRAFT'],payload:{headers:[{name:'To',value:'prospect@example.com'}]}}};
 const d={...policy,redis,KEY:key,config:async()=>({enabled:true,draftingEnabled:true,accounts:[{email:sender,brand:'Staffify',draftEnabled:true,owner:'Paul'}]}),access:async()=>{if(mailboxFailed)throw Error('expired');return 'token';},gmail:async(t,path,body,method)=>{calls.push({path,body,method});if(path.startsWith('messages?'))return {};if(path.startsWith('threads/'))return {messages:[prior]};if(path==='drafts'&&body){if(createUncertain)throw Error('connection lost');return draft;}if(path.startsWith('drafts/')){if(method==='PUT')draft={...draft,message:{...draft.message,payload:{headers:[{name:'To',value:''}]}}};return draft;}throw Error(path);},history:async()=>[prior],headers:m=>Object.fromEntries((m.payload?.headers||[]).map(h=>[h.name.toLowerCase(),h.value])),messageText:()=>'',mime:o=>JSON.stringify(o),compactMessage:m=>m,assertDraft:(d,r)=>{assert.equal(d.message.payload.headers[0].value,r||'');return d;},supply:async()=>0,canDraft:async()=>true,suppress:async()=>{},randomUUID:()=>Math.random().toString(),cronSecret:()=> 'test-secret'};
 const req={headers:{authorization:'Bearer test-secret'}};let response;const res={setHeader(){},status(code){this.code=code;return this;},json(body){response={code:this.code,body};assert.equal(db.has('outreach:cloud:lock'),false,'lock is released before response');return response;}};
 return {d,db,calls,run:async()=>{await makeWorker(d)(req,res);return response;},state:()=>db.get(key),setDraft:v=>draft=v};
}
const base={id:'one',recipient:'prospect@example.com',sender:'paul@trystaffify.com',owner:'Paul',sentTouches:1,status:'sent',lastSentAt:new Date(Date.now()-72*3600000).toISOString(),threadId:'thread',subject:'A useful task',bodyText:'hello'};
test('successful follow-up is saved once, read back and remains single on retry',async()=>{const h=harness({record:base});await h.run();assert.equal(h.state().records[0].status,'draft_saved');assert.equal(h.calls.filter(c=>c.path==='drafts').length,1);h.d.gmail=async(t,path)=>path.startsWith('messages?')?{}:path.startsWith('threads/')?{messages:[{id:'pending',draft:true}]}:{id:'draft',message:{id:'msg',payload:{headers:[{name:'To',value:base.recipient}]}}};await h.run();assert.equal(h.calls.filter(c=>c.path==='drafts').length,1);});
test('uncertain Gmail create is held and never blindly retried',async()=>{const h=harness({record:base,createUncertain:true});assert.equal((await h.run()).code,503);assert.equal(h.state().records[0].status,'draft_creation_pending');await h.run();assert.equal(h.state().records[0].status,'draft_creation_uncertain_hold');assert.equal(h.calls.filter(c=>c.path==='drafts').length,1);});
test('global suppression clears recipients and verifies draft before progressing',async()=>{const h=harness({record:{...base,status:'suppressed',draftId:'draft'}});await h.run();assert.equal(h.state().records[0].cloudHeld,true);assert.equal(h.calls.filter(c=>c.method==='PUT').length,1);assert.equal(h.calls.filter(c=>c.path==='drafts/draft').length,3);});
test('a stale sent draft pointer is archived without trying to modify sent mail',async()=>{const h=harness({record:{...base,status:'held_reply',draftId:'draft'}});h.setDraft({id:'draft',message:{id:'msg',labelIds:['SENT']}});await h.run();assert.equal(h.state().records[0].draftId,null);assert.equal(h.state().records[0].previousDraftId,'draft');assert.equal(h.calls.filter(c=>c.method==='PUT').length,0);});
test('missing mailbox access fails closed without any Gmail mutation',async()=>{const h=harness({record:base,mailboxFailed:true});assert.equal((await h.run()).code,503);assert.equal(h.calls.length,0);});
