import test from 'node:test';import assert from 'node:assert/strict';
import {sendDecision,sendQuota,sendOne} from '../api/_outreach-send.js';
import {dayKey} from '../api/_outreach-policy.js';
const now=Date.now(),sender='paul@trystaffify.com',to='owner@example.com';
const row={id:'one',owner:'Paul',sender,recipient:to,sentTouches:1,messageId:'draftmsg',draftId:'draft1',bodyText:'Useful follow-up',status:'draft_saved'};
const state=()=>({revision:1,records:[structuredClone(row)],assignments:[],pausedOwners:[],suppressions:[],creations:[{id:'one:2',status:'verified'}],sends:[]});
const prior={id:'sent1',replyId:'sent1',mailbox:sender,from:sender,to:[to],sent:true,date:now-72*3600000};
test('reply, STOP, wrong ownership, extra draft, cross-account and changed sent history all block sending',()=>{for(const [messages,reason] of [[[prior,{from:to,to:[sender],text:'yes tell me more'}],'human_reply_hold'],[[prior,{from:to,to:[sender],text:'STOP'}],'suppressed'],[[prior,{draft:true,id:'other',mailbox:sender}],'existing_draft_hold'],[[{...prior,mailbox:'other@example.com'}],'cross_account_history_hold'],[[],'send_history_changed_hold']])assert.equal(sendDecision(row,state(),messages,[sender],now),reason);const s=state();s.assignments=[{email:to,owner:'Madison'}];assert.equal(sendDecision(row,s,[prior],[sender],now),'ownership_hold');});
test('48-hour wait and four-send ceiling are enforced at send time',()=>{assert.equal(sendDecision(row,state(),[{...prior,date:now-47*3600000}],[sender],now),'followup_not_due_hold');assert.equal(sendDecision({...row,sentTouches:4},state(),Array.from({length:4},(_,i)=>({...prior,id:'s'+i,replyId:'s'+i})),[sender],now),'sequence_complete_hold');assert.equal(sendDecision(row,state(),[prior],[sender],now),null);});
test('send quotas combine manual evidence and durable reservations, deduplicating verified receipts',()=>{const s=state();s.sends=Array.from({length:50},(_,i)=>({id:'s'+i,day:dayKey(now),owner:'Madison',sender:'madison@staffifyhq.com',touch:i%4+1}));assert.equal(sendQuota({...row,owner:'Madison',sender:'madison@staffifyhq.com'},s,now),false);assert.equal(sendQuota({...row,owner:'Madison',sender:'madison@trystaffify.com'},s,now),true);assert.equal(sendQuota({...row,owner:'Madison',sender:'madison@staffifyhq.com'},s,now+86400000),true);s.sends=s.sends.map(x=>({...x,owner:'Paul',sender,touch:1}));assert.equal(sendQuota({...row,sentTouches:0},s,now),false);assert.equal(sendQuota(row,s,now),true);s.sends=[{id:'op',messageId:'sent1',day:dayKey(now),owner:'Madison',sender,touch:1}];s.records=[{...row,owner:'Madison',events:[{id:'sent1',kind:'sent',at:new Date(now).toISOString()}]}];assert.equal(sendQuota({...row,owner:'Madison'},s,now),true);});
function harness(fail=false){let s=state();const calls=[],journal=new Map();const cfg={enabled:true,sendingEnabled:true,accounts:[{email:sender,owner:'Paul'}]};const d={state:s,cfg,tokens:{[sender]:'token'},senders:[sender],KEY:'queue',redis:{get:async k=>k==='queue'?s:journal.get(k),set:async(k,v,o)=>{if(o?.nx&&journal.has(k))return null;journal.set(k,v);return 'OK';}},save:async v=>{v.revision++;s=v;return v;},gmail:async(t,path,b)=>{calls.push(path);if(path==='drafts/draft1')return {id:'draft1',message:{id:'draftmsg',labelIds:['DRAFT']}};if(path==='drafts/send'){if(fail)throw Error('timeout');return {id:'sent2'};}if(path==='messages/sent2?format=full')return {...prior,id:'sent2',date:Date.now(),threadId:'thread',text:row.bodyText,subject:'Re: useful'};throw Error(path);},history:async()=>[prior],compactMessage:m=>m,assertDraft:d=>d,messageText:()=>row.bodyText,canDraft:async()=>true,config:async()=>cfg,started:Date.now(),report:{},now:Date.parse('2026-09-29T16:00:00Z')};return {d,calls,get:()=>s};}
test('successful send is verified and journaled; rerunning does not send twice',async()=>{const h=harness();h.d.state=await sendOne(h.d);assert.equal(h.get().records[0].status,'sent');assert.equal(h.get().records[0].sentTouches,2);assert.equal(h.get().sends[0].status,'verified');h.d.state=await sendOne(h.d);assert.equal(h.calls.filter(p=>p==='drafts/send').length,1);});
test('uncertain send outcome is held without an automatic resend',async()=>{const h=harness(true);await assert.rejects(sendOne(h.d));h.d.state=h.get();await sendOne(h.d);assert.equal(h.get().records[0].status,'auto_send_uncertain_hold');assert.equal(h.calls.filter(p=>p==='drafts/send').length,1);});
test('last-moment global pause prevents send',async()=>{const h=harness();h.d.config=async()=>({enabled:false,sendingEnabled:true});await sendOne(h.d);assert.equal(h.calls.includes('drafts/send'),false);});
