import test from 'node:test';
import assert from 'node:assert/strict';
import {applyPaulPlan,applyMadisonPlan,residualTerms,eligibleResidualDay} from '../api/_madison-commission-plan.js';
const row=(n,extra={})=>({dealId:String(n),repEmail:'paul@staffifyhq.com',dealType:'va',closeDate:'2026-09-29',invoiceId:'new-'+n,placementUnits:[2100],base:2100,outstanding:0,leadSource:'house',status:'payable',...extra});
test('Paul earns 30% for all sources and 35% after four; all Paul mailboxes share one counter',()=>{const rows=[row(1),row(2,{leadSource:'self',repEmail:'paul@trystaffify.com'}),row(3,{leadSource:''}),row(4),row(5),row(6)];applyPaulPlan(rows);assert.deepEqual(rows.map(r=>r.rate),[30,30,30,30,35,35]);assert.equal(rows[2].status,'payable');assert.equal(rows[4].commission,735);});
test('historical placements neither change nor advance Paul’s fresh counter',()=>{const old=row(0,{closeDate:'2026-09-28',commission:735,rate:35});const original=JSON.stringify(old);const rows=[old,row(1),row(2),row(3),row(4)];applyPaulPlan(rows);assert.equal(JSON.stringify(old),original);assert.equal(rows[4].rate,30);assert.equal(rows[4].monthlyVerifiedPlacements,4);});
test('Paul monthly count resets, preserves paid payouts and remains idempotent',()=>{const rows=[row(1),row(2),row(3),row(4),row(5),row(6,{closeDate:'2026-10-01'}),row(7,{status:'paid_out',rate:25,commission:525})];applyPaulPlan(rows);assert.equal(rows[5].rate,30);assert.equal(rows[6].commission,525);const once=JSON.stringify(rows);applyPaulPlan(rows);assert.equal(JSON.stringify(rows),once);});
test('Paul has ongoing $1 residuals only for new placements; earlier terms stay intact',()=>{const before=residualTerms('paul@staffifyhq.com','2026-09-28'),after=residualTerms('paul@staffifyhq.com','2026-09-29');assert.equal(before.perHour,undefined);assert.equal(after.perHour,1);assert.equal(after.to,null);assert.equal(eligibleResidualDay('2028-01-01',after),true);assert.equal(eligibleResidualDay('2026-09-28',after),false);});
test('Paul’s counter does not alter Madison’s plan or combine their placements',()=>{const madison=row(1,{repEmail:'madison@gostaffify.com',closeDate:'2026-09-01'});const paul=row(2);applyMadisonPlan([madison,paul]);const previous=JSON.stringify(madison);applyPaulPlan([madison,paul]);assert.equal(JSON.stringify(madison),previous);assert.equal(madison.rate,20);assert.equal(paul.rate,30);assert.equal(paul.monthlyVerifiedPlacements,1);});

test('repeated new Paul placements map hours once, but historical/new client ambiguity needs review',async()=>{const {indexResidualDeal}=await import('../api/_madison-commission-plan.js');const index={};indexResidualDeal(index,'client',{dealId:'a',ownerEmail:'paul@staffifyhq.com',closeDate:'2026-09-29'});indexResidualDeal(index,'client',{dealId:'b',ownerEmail:'paul@trystaffify.com',closeDate:'2026-10-01'});assert.equal(index.client.dealId,'a');indexResidualDeal(index,'client',{dealId:'old',ownerEmail:'paul@staffifyhq.com',closeDate:'2026-08-01'});assert.equal(index.client,null);});
