import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import {canDraft} from './_outreach-crm.js';
export function publicIp(ip){if(isIP(ip)!==4)return false;const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a>=224);}
async function site(url){let u=new URL(url.startsWith('http')?url:'https://'+url);for(let i=0;i<4;i++){if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port&&!['80','443'].includes(u.port))throw Error('Invalid website');const ips=await lookup(u.hostname,{all:true});if(!ips.length||ips.some(x=>!publicIp(x.address)))throw Error('Non-public website');const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(5000)});if(r.status>=300&&r.status<400&&r.headers.get('location')){u=new URL(r.headers.get('location'),u);continue;}if(!r.ok)throw Error('Website unavailable');const reader=r.body.getReader();let raw='',bytes=0;while(bytes<500000){const {done,value}=await reader.read();if(done)break;bytes+=value.length;raw+=new TextDecoder().decode(value);}await reader.cancel();return {url:u.toString(),text:raw.replace(/<(script|style|noscript)[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')};}throw Error('Too many redirects');}
export async function supply(state,cfg){
 const token=process.env.HUBSPOT_TOKEN;if(!token)throw Error('CRM connection missing');
 const now=new Date().toISOString();
 const reserved=state.records.filter(r=>['reserved_for_madison_external','mailbox_connection_required'].includes(r.status)&&r.owner==='Madison'&&!r.sentTouches&&!(r.events||[]).some(e=>e.kind==='sent')&&(!r.draftId||r.cloudHeld)&&(!r.qualificationCheckedAt||Date.now()-Date.parse(r.qualificationCheckedAt)>86400000)).slice(0,5);
 const filters=reserved.length?[{propertyName:'email',operator:'IN',values:reserved.map(r=>r.recipient)}]:[{propertyName:'rep_email_verified',operator:'EQ',value:'verified'},{propertyName:'rep_lifecycle_state',operator:'EQ',value:'ACTIVE_OUTREACH'}];
 const r=await fetch('https://api.hubapi.com/crm/v3/objects/contacts/search',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({filterGroups:[{filters}],properties:['email','firstname','lastname','company','website'],limit:reserved.length?5:1,...(!reserved.length&&state.supplyCursor?{after:state.supplyCursor}:{})}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('CRM supply unavailable');const page=await r.json();
 if(!reserved.length)state.supplyCursor=page.paging?.next?.after||null;state.supplyCheckedAt=now;let added=0;
 for(const row of reserved){row.qualificationCheckedAt=now;row.qualificationReason='CRM record not found';}

 for(const c of page.results||[]){const p=c.properties,email=String(p.email||'').toLowerCase();const existing=state.records.find(r=>r.recipient===email);if(existing&&reserved.includes(existing))existing.qualificationReason='Missing company or website, duplicate company, or ineligible state';if(!email||!p.company||!p.website||existing&&!['awaiting_qualification','reserved_for_madison_external','mailbox_connection_required'].includes(existing.status)||state.records.some(r=>r.recipient!==email&&r.company?.toLowerCase()===p.company.toLowerCase()))continue;if(existing&&(existing.sentTouches||(existing.events||[]).some(e=>e.kind==='sent')||existing.draftId&&!existing.cloudHeld))continue;
  const assigned=state.assignments.find(a=>a.email===email);const owner=assigned?.owner||existing?.owner||(Number(String(c.id).slice(-1))%2?'Madison':'Paul');if(state.pausedOwners.includes(owner)||state.suppressions.includes(email))continue;const senders=cfg.accounts.filter(a=>a.owner===owner&&a.brand==='Staffify'&&a.draftEnabled);if(!senders.length)continue;const sender=senders[state.records.filter(r=>r.owner===owner).length%senders.length].email;
  const row={id:existing?.id||'cloud-'+c.id,hubspotId:c.id,recipient:email,company:p.company,owner,sender,sentTouches:0,status:'prepared',createdAt:new Date().toISOString()};
  if(existing)existing.qualificationReason='CRM eligibility check failed';if(!await canDraft(row))continue;let evidence;try{evidence=await site(p.website);}catch{if(existing)existing.qualificationReason='Agency website unavailable';continue;}
  const m=/real[ -]estate.{0,50}(photograph|videograph|media)|(?:property|architectural) photography/i.exec(evidence.text);if(!m){if(existing)existing.qualificationReason='Website does not establish real estate media services';continue;}
  const agencyKey=new URL(evidence.url).hostname.replace(/^www\./,'');if(state.assignments.some(a=>a.agencyKey===agencyKey&&a.email!==email)||state.records.some(r=>r.agencyKey===agencyKey&&r.recipient!==email))continue;
  const first=p.firstname&&evidence.text.toLowerCase().includes(p.firstname.toLowerCase())&&evidence.text.toLowerCase().includes(email)?p.firstname:'there';
  const intro=owner==='Madison'?"I'm Madison with Staffify. I work closely with our CEO, Paul, who grew Flylisted, his real estate marketing agency, to seven figures annually across six states.":"I'm Paul, founder of Flylisted and Staffify. I built Flylisted to over $6 million in lifetime sales and a comfortable $1.2 million in annual sales, with a 40% margin, operating across six states.";
  Object.assign(row,{agencyKey,verifiedFirstName:first==='there'?null:first,qualificationApproved:true,subject:'A practical handoff for '+p.company,bodyText:['Hi '+first+',',intro,'We put together 15 tasks real estate media agency owners can hand off, drawn from the project manager role at Flylisted. Each includes what done looks like and what the owner still approves.','https://www.gostaffify.com/blog/real-estate-photography-tasks-to-delegate/','One example is tracking every photo revision against a written checklist and bringing the owner only the exceptions. Which handoff still lands on your desk?',owner+'\nStaffify',"If you'd prefer no more emails, just let me know."].join('\n\n'),source:{url:evidence.url,checkedAt:new Date().toISOString(),excerpt:evidence.text.slice(Math.max(0,m.index-60),m.index+160)}});
  if(existing){Object.assign(existing,{legacyMailbox:{sender:existing.sender,threadId:existing.threadId,draftId:existing.draftId,messageId:existing.messageId,events:existing.events||[],status:existing.status},threadId:null,draftId:null,messageId:null,events:[],cloudHeld:false,verifiedSentTouches:0,lastSentAt:null,nextEligibleAt:null,callReady:false,qualificationCheckedAt:now,qualificationReason:'Approved for connected mailbox'},row);}else state.records.push(row);if(!assigned)state.assignments.push({hubspotId:c.id,email,company:p.company,agencyKey,owner,reservedAt:new Date().toISOString()});added++;
 }
 return added;
}
