import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
import {redis} from './_auth.js';
export const CONFIG='outreach:cloud:config';
export const DEFAULT_ACCOUNTS=['paul@trystaffify.com','paul@staffifyhq.com','hello@gostaffify.com','paul@hirestaffify.com','madison@gostaffify.com','madison@staffifyhq.com','madison@trystaffify.com','madison@hirestaffify.com','madison.sterling@trystaffify.com','paul@tryfoundryhq.com','paul@getfoundrybuilds.com','paul@getfoundrysites.com'];
export const SCOPES=['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.compose'];
export const clientId=()=>process.env.OUTREACH_GOOGLE_CLIENT_ID||process.env.GOOGLE_CLIENT_ID;
export const clientSecret=()=>process.env.OUTREACH_GOOGLE_CLIENT_SECRET||process.env.GOOGLE_CLIENT_SECRET;
function key(){if(!process.env.CRON_SECRET)throw Error('Missing encryption secret');return createHash('sha256').update('staffify-outreach-tokens:'+process.env.CRON_SECRET).digest();}
export function seal(value){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]);return {iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),body:body.toString('base64')};}
export function unseal(value){const d=createDecipheriv('aes-256-gcm',key(),Buffer.from(value.iv,'base64'));d.setAuthTag(Buffer.from(value.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(value.body,'base64')),d.final()]).toString());}
export async function config(){return await redis.get(CONFIG)||{enabled:false,expectedAccounts:12,accounts:DEFAULT_ACCOUNTS.map(email=>({email,owner:email.startsWith('madison')?'Madison':'Paul',dailyLimit:50,brand:email.includes('foundry')?'Foundry':'Staffify',draftEnabled:!email.includes('foundry')})),updatedAt:null};}
export async function access(email){const saved=await redis.get('outreach:oauth:'+email);if(!saved)throw Error('Mailbox authorization missing: '+email);const tok=unseal(saved);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:clientId(),client_secret:clientSecret(),grant_type:'refresh_token',refresh_token:tok.refresh_token}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Mailbox authorization expired: '+email);return (await r.json()).access_token;}
export async function gmail(token,path,body,method){if(/\/send(?:\?|$)/.test(path))throw Error('Sending is disabled');const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Gmail request failed: '+r.status);return r.status===204?{}:r.json();}
export async function history(token,email){let ids=[],pageToken;do{const q='in:anywhere -in:drafts {from:'+email+' to:'+email+'}';const p=new URLSearchParams({q,maxResults:'100',...(pageToken?{pageToken}:{})});const r=await gmail(token,'messages?'+p);ids.push(...(r.messages||[]));pageToken=r.nextPageToken;if(ids.length>200)throw Error('Extensive prior history; manual review required');}while(pageToken);return Promise.all(ids.map(m=>gmail(token,'messages/'+m.id+'?format=full')));}
export function headers(message){return Object.fromEntries((message.payload?.headers||[]).map(h=>[h.name.toLowerCase(),h.value]));}
export function messageText(message){let parts=[];function walk(p){if(p?.body?.data)parts.push(Buffer.from(p.body.data,'base64url').toString());for(const c of p?.parts||[])walk(c);}walk(message.payload);return parts.join('\n').replace(/<[^>]+>/g,' ').split(/\nOn .+wrote:|-----Original Message-----/)[0];}
export function mime({sender,to,subject,body,id,replyId}){for(const s of [sender,to,subject,id,replyId||''])if(/[\r\n]/.test(s))throw Error('Invalid mail header');return Buffer.from(['From: '+sender,'To: '+to,'Subject: '+subject,'Message-ID: <'+id+'@gostaffify.com>',...(replyId?['In-Reply-To: '+replyId,'References: '+replyId]:[]),'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',Buffer.from(body).toString('base64')].join('\r\n')).toString('base64url');}
