import {supplyDealFollowups} from './_deal-followups.js';
import {maintainClients} from './_outreach-maintenance.js';
import {randomUUID} from 'node:crypto';
import {redis} from './_auth.js';
import {KEY} from './_outreach-queue.js';
import {config,access,gmail,history,headers,messageText,mime,compactMessage,assertDraft} from './_outreach-gmail.js';
import {supply} from './_outreach-supply.js';
import {canDraft,suppress} from './_outreach-crm.js';
import {eligible,quota,dayKey,classify,followup,reconcileThread,callReady} from './_outreach-policy.js';
import {makeWorker} from './_outreach-worker-core.js';
export default makeWorker({dealSupply:supplyDealFollowups,maintain:()=>maintainClients({redis}),redis,KEY,config,access,gmail,history,headers,messageText,mime,compactMessage,assertDraft,supply,canDraft,suppress,eligible,quota,dayKey,classify,followup,reconcileThread,callReady,randomUUID,cronSecret:()=>process.env.CRON_SECRET});
